#ifndef H_${PROJECT_NAME}_CONFIG
#define H_${PROJECT_NAME}_CONFIG

#define PQUANTUM_VERSION_MAJOR ${${PROJECT_NAME}_VERSION_MAJOR}
#define PQUANTUM_VERSION_MINOR ${${PROJECT_NAME}_VERSION_MINOR}
#define PQUANTUM_VERSION_PATCH ${${PROJECT_NAME}_VERSION_PATCH}
#define PQUANTUM_VERSION_TWEAK ${${PROJECT_NAME}_VERSION_TWEAK}

#define PQUANTUM_EXAMPLES_DIRECTORY "${${PROJECT_NAME}_EXAMPLES_DIR}"

#endif
