//
// Created by jayz on 07.04.20.
//

#ifndef PQUANTUM_CALCULATION_FIELD_POLYNOMIAL_HPP
#define PQUANTUM_CALCULATION_FIELD_POLYNOMIAL_HPP

namespace PQuantum::calculation {
}

#endif //PQUANTUM_CALCULATION_FIELD_POLYNOMIAL_HPP
